# -*- coding: utf-8 -*-
"""comparision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMjfmZEvzGERqvqChb-Xd8zDpE79f7-J
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.8, random_state=42
)

models = {
    "Linear Regression": LinearRegression(),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)

    if name == "Linear Regression":
        preds = model.predict(X_test)
        preds = np.round(preds).astype(int)
    else:
        preds = model.predict(X_test)

    acc = accuracy_score(y_test, preds)
    results.append([name, acc])

    print("="*40)
    print(f"Model: {name}")
    print("Accuracy:", acc)

df = pd.DataFrame(results, columns=["Model", "Accuracy"])
print("\nFinal Comparison Table")
print(df)

