# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0z3jqJdz1vG8gIL5wuKPxH2racKScuZ

WITHOUT USING FUNCTION
"""

import kagglehub
import os
import csv
import numpy as np

path = kagglehub.dataset_download("uciml/iris")
print("Dataset path:", path)

X = []
y = []

with open(os.path.join(path, "Iris.csv"), "r") as file:
    reader = csv.reader(file)
    next(reader)
    for row in reader:
        X.append([float(row[1]), float(row[2]), float(row[3]), float(row[4])])
        y.append(row[5])

label_map = {
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
}

y = [label_map[label] for label in y]

X = np.array(X)
y = np.array(y)

split = int(0.2 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

def euclidean_distance(a, b):
    s = 0
    for i in range(len(a)):
        s += (a[i] - b[i]) ** 2
    return s ** 0.5

def knn_predict(X_train, y_train, test_point, k=3):
    distances = []
    for i in range(len(X_train)):
        dist = euclidean_distance(X_train[i], test_point)
        distances.append((dist, y_train[i]))
    distances.sort(key=lambda x: x[0])
    k_nearest = distances[:k]

    votes = {}
    for _, label in k_nearest:
        votes[label] = votes.get(label, 0) + 1

    return max(votes, key=votes.get)

y_pred = []
for i in range(len(X_test)):
    y_pred.append(knn_predict(X_train, y_train, X_test[i], k=3))

confusion_matrix = [[0, 0, 0],
                    [0, 0, 0],
                    [0, 0, 0]]

correct = 0
for i in range(len(y_test)):
    confusion_matrix[y_test[i]][y_pred[i]] += 1
    if y_test[i] == y_pred[i]:
        correct += 1

accuracy = correct / len(y_test)

print("\nConfusion Matrix:")
for row in confusion_matrix:
    print(row)

print("\nAccuracy:", accuracy * 100, "%")

import kagglehub
import os
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

path = kagglehub.dataset_download("uciml/iris")
print("Dataset path:", path)

data = pd.read_csv(os.path.join(path, "Iris.csv"))

X = data.iloc[:, 1:5].values
y = data.iloc[:, 5].values

label_map = {
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
}
y = np.array([label_map[label] for label in y])

split = int(0.2 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)

print("\nAccuracy:", accuracy * 100, "%")

