# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgnhPnubS-w5dGP5UhFZaj1BuqZqyxB6
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_excel("/content/sample_data/Book2.xlsx")


X = df.iloc[:, [0]]
y = df.iloc[:, 1]

model = LinearRegression()
model.fit(X, y)

print("Intercept (a):", model.intercept_)
print("Slope (b):", model.coef_[0])

import pandas as pd

df = pd.read_excel("/content/sample_data/Book2.xlsx")

# convert columns to lists
x = list(df.iloc[:, 0])
y = list(df.iloc[:, 1])

n = len(x)

sx = sum(x)
sy = sum(y)
sxy = sum(x[i] * y[i] for i in range(n))
sx2 = sum(a * a for a in x)

b = (n * sxy - sx * sy) / (n * sx2 - sx * sx)
a = (sy - b * sx) / n

print("Intercept a =", a)
print("Slope b =", b)

x_new = 5
y_pred = a + b * x_new
print("Predicted y =", y_pred)

